# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hydra

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - git checkout -- go.sum

builds:
  -
    id: hydra-sqlite-darwin
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/hydra/driver/config.Version={{.Tag}} -X github.com/ory/hydra/driver/config.Commit={{.FullCommit}} -X github.com/ory/hydra/driver/config.Date={{.Date}}
      # - "-extldflags '-static'"
    binary: hydra
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
    goos:
      - darwin

  -
    id: hydra-sqlite-linux
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/hydra/driver/config.Version={{.Tag}} -X github.com/ory/hydra/driver/config.Commit={{.FullCommit}} -X github.com/ory/hydra/driver/config.Date={{.Date}}
    binary: hydra
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
  -
    id: hydra-sqlite-linux-libmusl
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/hydra/driver/config.Version={{.Tag}} -X github.com/ory/hydra/driver/config.Commit={{.FullCommit}} -X github.com/ory/hydra/driver/config.Date={{.Date}}
    binary: hydra
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    goarch:
      - amd64
    goos:
      - linux
  -
    id: hydra-sqlite-windows
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/hydra/driver/config.Version={{.Tag}} -X github.com/ory/hydra/driver/config.Commit={{.FullCommit}} -X github.com/ory/hydra/driver/config.Date={{.Date}}
      - "-extldflags '-static'"
    binary: hydra
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows

  -
    id: hydra
    ldflags:
      - -s -w -X github.com/ory/hydra/driver/config.Version={{.Tag}} -X github.com/ory/hydra/driver/config.Commit={{.FullCommit}} -X github.com/ory/hydra/driver/config.Date={{.Date}}
    binary: hydra
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  - id: hydra-sqlite
    builds:
      - hydra-sqlite-windows
      - hydra-sqlite-darwin
      - hydra-sqlite-linux
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md
    name_template: "{{ .ProjectName }}_{{ .Version }}-sqlite_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: hydra-sqlite-libmusl
    builds:
      - hydra-sqlite-linux-libmusl
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md
    name_template: "{{ .ProjectName }}_{{ .Version }}-sqlite-libmusl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: hydra
    builds:
      - hydra
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - ci skip
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: ory
      name: homebrew-hydra
    ids:
      - hydra-sqlite
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: 3372410+aeneasr@users.noreply.github.com
    install: |
      bin.install "hydra"

scoop:
  bucket:
    owner: ory
    name: scoop-hydra
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: 3372410+aeneasr@users.noreply.github.com

checksum:
  algorithm: sha256

dockers:
  - dockerfile: .docker/Dockerfile-sqlite
    ids:
      - hydra-sqlite-linux-libmusl
    image_templates:
      - "oryd/hydra:v{{ .Major }}-sqlite"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}-sqlite"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-sqlite"
      - "oryd/hydra:{{ .Tag }}-sqlite"
      - "oryd/hydra:latest-sqlite"
  - dockerfile: .docker/Dockerfile-scratch
    ids:
      - hydra
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
    image_templates:
      - "oryd/hydra:v{{ .Major }}"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "oryd/hydra:{{ .Tag }}"
      - "oryd/hydra:latest"
  - dockerfile: .docker/Dockerfile-alpine
    ids:
      - hydra
    image_templates:
      - "oryd/hydra:v{{ .Major }}-alpine"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}-alpine"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-alpine"
      - "oryd/hydra:{{ .Tag }}-alpine"
      - "oryd/hydra:latest-alpine"

release:
  prerelease: auto
  name_template: "{{.Tag}}"
  ids:
    - hydra-sqlite
    - hydra-sqlite-libmusl
    - hydra
